### ISSUE TITLE
Примитивные критерии

### ISSUE THREAD

**Issue by zmm** [OSLL/web_speech_trainer#119]
Примитивные критерии - мин планка количества слов на слайде, минимальное и максимальное количество рассказанных слайдов

**Comment by HadronCollider** [comment]
Задача-демо: http://e.moevm.info/mod/lti/view.php?id=1407

**Comment by zmm** [comment]
Провел тренировку, сказал 0 слов, но критерий на мин. число слов выдал мне 1 . Давайте сделаем копию NumberWordOnSlideCriterion, ориентированную именно на слова из транскрипции
https://speech-trainer.cub-it.org/trainings/statistics/60ed9c3617b4ab21e8b32f36/?transcription=true

**Comment by HadronCollider** [comment]
@zmm 
- Добавлен критерий по количество распознанных слов на каждом слайде #242 (задеплоено, https://speech-trainer.cub-it.org/trainings/statistics/60ee9fbcce66c662eebdd280/?transcription=true)
- Найден баг разбора аудио на слайды #241
