### ISSUE TITLE
Аудиозаписи тренировок нельзя пролистывать

### ISSUE THREAD

**Issue by zmm** [OSLL/web_speech_trainer#159]
https://speech-trainer.cub-it.org/training_statistics/606d69cb6c654e70ed11dcf0/

**Comment by Plyushchenko** [comment]
https://ru.stackoverflow.com/questions/935685/html5-audio-%D0%9D%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%BE%D1%82%D0%BA%D0%B0-%D0%B2-%D0%A5%D1%80%D0%BE%D0%BC%D0%B5
https://ru.stackoverflow.com/questions/597264/html5-audio-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%BE%D1%82%D0%BA%D0%B0-%D0%B2-google-chrome
