### ISSUE TITLE
Скрипты для построения графиков/гистограмм по всей бд

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/web_speech_trainer#235]
скорость речи, время на слайдах и пр.

**Comment by zmm** [comment]
Дмитрий, сделайте, пожалуйста, краткую инструкцию как запустить скрипты + дайте примеры скринов гистограмм.

**Comment by HadronCollider** [comment]
https://github.com/OSLL/web_speech_trainer/pull/239#issue-688021510

- Команда
```bash
./scripts/visualize.sh
```
- Результат: в директории ` visualization/retults/<current_date>`, графики:

  - [x] - распределение и среднее время обработки тренировки/аудио/презентации, время обработки аудио на секунду записи, время обработки презентации на слайд
  - [x] - распределение и среднее количество распознанных на аудиозаписи слов, слайдов в презентации, слов на слайде
  - [x] - распределение и средняя длительность записи, общей оценки за тренировки, оценки по каждому критерию, среднее время нахождения на слайдах

- [Пример построенных диаграмм](https://drive.google.com/drive/folders/1Zy1WVhM7IvRsNnAxXVtBZFdGpBaFpTXn?usp=sharing)

**Comment by zmm** [comment]
не хватает четырех либ: pandas matplotlib bson pymongo

ubuntu@ip-172-31-40-72:/mnt/ws/workspace/workspace/WST_deploy$ ./scripts/visualize.sh 
Traceback (most recent call last):
  File "visualization.py", line 108, in <module>
    df = timestamp_to_datetime(df)
  File "visualization.py", line 24, in timestamp_to_datetime
    df[field] = [timestamp.time if type(timestamp) != datetime else timestamp.timestamp() for timestamp in df[field]]
  File "visualization.py", line 24, in <listcomp>
    df[field] = [timestamp.time if type(timestamp) != datetime else timestamp.timestamp() for timestamp in df[field]]
AttributeError: 'float' object has no attribute 'time'
/mnt/ws/workspace/workspace/WST_deploy

очевидно нужно

**Comment by HadronCollider** [comment]
Для проверки на деплое - обновить мастер (вмержен после передеплоя - не затрагивает веб)

**Comment by HadronCollider** [comment]
Добавить скрипт установки python-зависимостей

**Comment by HadronCollider** [comment]
json_load(file)
