### ISSUE TITLE
Интерфейс для повторного воспроизведения тренировки 

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/web_speech_trainer#236]
Отображение слайдов, таймкоды

**Comment by zmm** [comment]
ТАймкоды завязаны на https://github.com/OSLL/web_speech_trainer/issues/159

**Comment by HadronCollider** [comment]
https://github.com/OSLL/web_speech_trainer/wiki/%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B2%D0%BE%D1%81%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F-%D1%82%D1%80%D0%B5%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8

**Comment by zmm** [comment]
Отдельная страница не нужна - нужно уместить повторный просмотр на странице тренировки

**Comment by zmm** [comment]
Вносите задачи + добавьте задачи для поддержки таймкодов / номеров слайдов в качестве параметров ссылки на страницу тренировки

**Comment by HadronCollider** [comment]
https://github.com/OSLL/web_speech_trainer/milestone/1
