### ISSUE TITLE
Поддержку pptx

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/web_speech_trainer#237]
В основном - отображение на клиенте
+ парсинг

**Comment by HadronCollider** [comment]
https://github.com/OSLL/web_speech_trainer/wiki/%D0%9F%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0-PPTX

**Comment by zmm** [comment]
Идем по пути конвертации в pdf и его отображения . В случае если pptx, то будет хранить и исходный файл, и преобразованный
Заводите необходимые задачи + 1) поддержка ограничения на тип файла в виде параметра payload в задачах 2) динамически показываем (В зависимости от payload ) ограничения и предупреждения про то, какие форматы можно загружать

**Comment by HadronCollider** [comment]
https://github.com/OSLL/web_speech_trainer/milestone/1
