### ISSUE TITLE
Уведомление о поддерживаемых форматах

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/web_speech_trainer#251]
from https://github.com/OSLL/web_speech_trainer/issues/237

В зависимости от payload задачи показывать ограничения и предупреждения про то, какие форматы можно загружать

**Comment by HadronCollider** [comment]
http://e.moevm.info/mod/lti/view.php?id=1524

**Comment by zmm** [comment]
дефолтное поведение, если параметр формата не задан
валидация значения параметра
добавление в диалог открытия файлов (загрузка презентации) масок на указанные типы https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/file#limiting_accepted_file_types
гифка для ожидания конвертации в pdf

**Comment by HadronCollider** [comment]
- [x] дефолтное поведение, если параметр формата не задан (https://github.com/OSLL/web_speech_trainer/pull/293/files#diff-deddbccda2f93fa5fd9e822f379d81834395985fac136cb16d643c85684f02c8R49-R53)
- [x] валидация значения параметра (https://github.com/OSLL/web_speech_trainer/pull/293/files#diff-9efe19abaa8252247c0011f90f9f644beb33bd8ac7dd84953ba4fca92b439812R44)
- [x] добавление в диалог открытия файлов (загрузка презентации) масок на указанные типы (https://github.com/OSLL/web_speech_trainer/pull/293/files#diff-deddbccda2f93fa5fd9e822f379d81834395985fac136cb16d643c85684f02c8R48)
- [x] гифка для ожидания конвертации в pdf (https://github.com/OSLL/web_speech_trainer/pull/293/files#diff-11de0ddb0677be3c6f14500b191ef269b2d3514cbf1881afb11f513a99605cb5R17)

**Comment by zmm** [comment]
Финальный штрих - плашку "Презентация будет преобразована в PDF-формат. Это может занять некоторое время!" нужно убирать (а лучше заменять на текст "Нажмите ... чтобы начать") после окончания конвертации

**Comment by HadronCollider** [comment]
@zmm после окончания конвертации происходит перенаправление на страницу тренировки (так же, как и при окончании загрузки PDF)

**Comment by HadronCollider** [comment]
Дополнить сообщение о конвертации необходимостью нажать кнопку "Начать"
