### ISSUE TITLE
changeTrainingStatsURL is not defined на странице тренировки

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/web_speech_trainer#275]

**Comment by zmm** [comment]
![image](https://user-images.githubusercontent.com/717575/129378536-9dc0ac98-7f44-4057-82ec-b6fd64850e1d.png)
![image](https://user-images.githubusercontent.com/717575/129378788-05810d84-9d9e-4db9-8c3e-ed33228d3005.png)

**Comment by zmm** [comment]
Сообщение в консоли ушло, но микрофон по-прежнему недоступен. Проверял в Chrome Версия 91.0.4472.164 (Официальная сборка), (64 бит)
