### ISSUE TITLE
Интерфейс создания экземпляров критериев

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/web_speech_trainer#296]

**Comment by HadronCollider** [comment]
- [x] Реализовано создание новых критериев
Дополнительно:
- [x] Обновлена структура БД
- [x] Реализовано обновление существующих в БД критериев
- [x] Реализованы подсказки на основании базового критерия и проверка корректности критерия перед сохранением

**Comment by zmm** [comment]
Как можно проверить данную задачу?

**Comment by HadronCollider** [comment]
Ссылка на создание нового критерия и редактирование на:
- https://speech-trainer.cub-it.org/criterion/list/ (можно попасть со страницы админа https://speech-trainer.cub-it.org/admin/)
