### ISSUE TITLE
Проверка необходимости denoize и wav-convert

### ISSUE THREAD

**Issue by HadronCollider** [OSLL/web_speech_trainer#401]
https://github.com/OSLL/web_speech_trainer/pull/388#discussion_r1522055745

**Comment by arhihihipov** [comment]
**Medium модель**:
- С предобработкой: [' Добрый', ' день,', ' все', ' хорошо?', ' Я', ' сижу', ' дома.']

- Без предобработки: [' Добрый', ' день!', ' Всё', ' хорошо?', ' Я', ' сижу', ' дома.']

На картинке сравнил результат работы на своём докладе. Цветом выделены различия. Зелёный цвет -- без предобработки, желтый цвет -- с предобработкой. Можно заметить, что после предобработки распознавание начинает косячить
![image](https://github.com/OSLL/web_speech_trainer/assets/71722818/379fd564-7684-4eef-8d17-4fbcc2716373)

**Tiny модель**:

- С предобработкой: [' Добрый', ' день!', ' Всё', ' хорошо!', ' Я', ' всё', ' зудовому!']

- Без предобработки: [' Добрый', ' день.', ' Всё', ' хорошо.', ' Я', ' сейчас', ' у', ' дома.']

- С предобработкой: [' Всем', ' здравствуйте.', ' Меня', ' зовут', ' Архипов', ' Вадим', ' и', ' всем', ' вам', ' у', ' него', ' сегодня', ' снего', ' доклада.']

- Без предобрабоки: [' Всем', ' здравствуйте!', ' Меня', ' зовут', ' Архипов', ' Вадим', ' и', ' тема', ' моего', ' сегодняшнего', ' доклада,']

На основании того, что я вижу, можно сделать вывод, что конвертация в wav и прогон через Denoiser не требуется, поскольку эти преобразования снижают точность распознавания
